config/routes.rb
Rails.application.routes.draw do
  root "home#index"

  resources :brew_batches, only: :index
  get "voices/:token", to: "voices#show", as: :voice
  get "voices/:token/claim", to: "voices#new_claim", as: :claim_voice
  patch "voices/:token/claim", to: "voices#create_claim"

  namespace :admin do
    get "/", to: "pages#dashboard"
    get "/users", to: "pages#users"
    get "/voices", to: "pages#voices"

    resources :brew_batches, except: [:show]
    patch "brew_batches/:id/issue_voices", to: "brew_batches#issue_voices", as: :issue_voices
    get "brew_batches/:id/show_labels", to: "brew_batches#show_labels", as: :show_labels

    resources :releases do
      member do
        patch :notify
      end
    end
  end
end

app/models/brew_batch.rb
class BrewBatch < ApplicationRecord
  has_many :voices, dependent: :restrict_with_exception

  validates :serial_number, presence: true

  scope :published, -> { where(published_at: Time.zone.parse("2018-12-31")..Time.zone.now) }

  def issue_voices!(amount)
    amount.times do
      voices << Voice.new(token: SecureRandom.hex)
    end
    save!
  end
end

app/controllers/admin/brew_batches_controller.rb
module Admin
  class BrewBatchesController < AdminController
    before_action :set_brew_batch, only: %i[edit update destroy issue_voices show_labels]

    # GET /brew_batches
    def index
      @brew_batches = BrewBatch.order(serial_number: :desc)
    end

    # GET /brew_batches/new
    def new
      @brew_batch = BrewBatch.new
    end

    # GET /brew_batches/1/edit
    def edit
    end

    # POST /brew_batches
    def create
      @brew_batch = BrewBatch.new(brew_batch_params)

      respond_to do |format|
        if @brew_batch.save
          format.html { redirect_to admin_brew_batches_url, notice: "Batch was successfully created." }
        else
          format.html { render :new }
        end
      end
    end

    # PATCH/PUT /brew_batches/1
    def update
      respond_to do |format|
        if @brew_batch.update(brew_batch_params)
          format.html { redirect_to admin_brew_batches_url, notice: "Batch was successfully updated." }
        else
          format.html { render :edit }
        end
      end
    end

    # DELETE /brew_batches/1
    def destroy
      if @brew_batch.destroy
        redirect_to admin_brew_batches_url, notice: "Batch was successfully destroyed."
      else
        redirect_to admin_brew_batches_url, error: "Batch could not be created."
      end
    end

    def issue_voices
      if @brew_batch.voices.any?
        redirect_to admin_brew_batches_url, notice: "There are already voices issued. No new ones have been created."
        return
      end

      issue_voices_amount = params[:issue_voices_amount].to_i
      if issue_voices_amount.positive?
        @brew_batch.issue_voices!(issue_voices_amount)
        redirect_to admin_brew_batches_url, notice: "Issued #{issue_voices_amount} voices for #{@brew_batch.name}"
      else
        redirect_to admin_brew_batches_url, error: "No correct amount. No voices issued."
      end
    end

    def show_labels
      respond_to do |format|
        format.xlsx do
          headers["Content-Disposition"] = "attachment; filename=\"#{@brew_batch.serial_number}-Voices.xlsx\""
        end
      end
    end

    private

    # Use callbacks to share common setup or constraints between actions.
    def set_brew_batch
      @brew_batch = BrewBatch.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def brew_batch_params
      params.require(:brew_batch).permit(:serial_number, :name, :description, :published_at, :published_amount)
    end
  end
end

app/controllers/brew_batches_controller.rb
class BrewBatchesController < ApplicationController
  # GET /brew_batches
  def index
    @brew_batches = BrewBatch.published.order(published_at: :desc)
  end
end

app/views/admin/brew_batches/_form.html.erb
<%= form_with(model: [:admin, brew_batch], local: true) do |form| %>
  <% if brew_batch.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(brew_batch.errors.count, "error") %> prohibited this brew_batch from being saved:</h2>

      <ul>
      <% brew_batch.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :serial_number %>
    <%= form.text_field :serial_number, class: 'form-control', pattern: 'BG\d\d-.*', placeholder: "BG#{Time.zone.now.year.to_s[-2..-1]}-??" %>
  </div>

  <div class="form-group">
    <%= form.label :name %>
    <%= form.text_field :name, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :description %>
    <%= form.text_area :description, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :published_at %>
    <%= form.date_field :published_at, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :published_amount %>
    <%= form.text_field :published_amount, class: 'form-control' %>
  </div>

  <div class="actions">
    <%= form.submit class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/admin/brew_batches/_issue_voices_form.html.erb
<%= form_with(url: { action: "issue_voices", id: brew_batch.id }, method: :patch) do |form| %>
  <div class="form-group">
    <%= form.label :issue_voices_amount %>
    <%= form.number_field :issue_voices_amount, class: 'form-control' %>
  </div>

  <div class="actions">
    <%= form.submit 'Issue voices', class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/admin/brew_batches/edit.html.erb
<h1>Editing Brew Batch</h1>

<%= render 'form', brew_batch: @brew_batch %>

<hr>

<% if @brew_batch.voices.empty? %>
  <%= render 'issue_voices_form', brew_batch: @brew_batch %>
<% else %>
  <p>Issued voices: <%= @brew_batch.voices.count %></p>
<% end %>

<%= link_to 'Back', admin_brew_batches_path %>

app/views/admin/brew_batches/index.html.erb
<h1>Brew Batches</h1>

<table class="table">
  <thead>
    <tr>
      <th>Batch-Bez.</th>
      <th>Name</th>
      <th>Description</th>
      <th>Published</th>
      <th>Voices</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @brew_batches.each do |brew_batch| %>
      <tr>
        <td><%= brew_batch.serial_number %></td>
        <td><%= brew_batch.name %></td>
        <td><%= brew_batch.description.first(100) %>…</td>
        <td><%= brew_batch.published_at&.strftime('%Y-%m-%d') %></td>
        <td>
          <%= brew_batch.voices.count %>
          <%= link_to '🏷', admin_show_labels_path(brew_batch, format: :xlsx) %>
        </td>
        <td><%= link_to 'Edit', edit_admin_brew_batch_path(brew_batch) %></td>
        <td><%= link_to 'Destroy', [:admin, brew_batch], method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Brew Batch', new_admin_brew_batch_path %>

app/views/admin/brew_batches/new.html.erb
<h1>New Brew Batch</h1>

<%= render 'form', brew_batch: @brew_batch %>

<%= link_to 'Back', admin_brew_batches_path %>