config/routes.rb
Rails.application.routes.draw do
  root "home#index"

  resources :brew_batches, only: :index
  get "voices/:token", to: "voices#show", as: :voice
  get "voices/:token/claim", to: "voices#new_claim", as: :claim_voice
  patch "voices/:token/claim", to: "voices#create_claim"

  namespace :admin do
    get "/", to: "pages#dashboard"
    get "/users", to: "pages#users"
    get "/voices", to: "pages#voices"

    resources :brew_batches, except: [:show]
    patch "brew_batches/:id/issue_voices", to: "brew_batches#issue_voices", as: :issue_voices
    get "brew_batches/:id/show_labels", to: "brew_batches#show_labels", as: :show_labels

    resources :releases do
      member do
        patch :notify
      end
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @stakes = {
      total_voice_count: 50_000,
      my_voice_count: 42,
      my_permille_share: ((42.0 / 50_000.0) * 1000.0).round(2)
    }
  end
end

app/views/home/index.html.erb
<section>
  <h1>Brauzeugen</h1>

  <p>Guten Tag, Wanderer! Du hast dir ein
    <strong><%= link_to 'gutes Bier', brew_batches_path %></strong> verdient – und
    genau solches brauen wir. Der richtige Einsatz feiner Nasen und
    geschickter Handwerkskunst führt zu unserem zerbrechlichen und
    doch so starken Gebräu.</p>
  <p></p>


  <p>Du bist herzlich zum Verkosten eingeladen. Melde
    dich bei:
    <a href="mailto:mail@brauzeugen.ch">mail@brauzeugen.ch</a>.
  </p>

  <p>Bis dann,<br>Brauschmid und EXperte</p>

  <%= image_tag 'bar-1299049.svg', class: 'illustration', alt: t('.barrel_image') %>
</section>

<section>
  <h2>Wir sind</h2>
  <p>
    Wir sind Geniesser, welche während der gemeinsamen
    Studienzeit in Rapperswil die Liebe zum guten Bier gefunden haben.
    Dank der VSHSR-Brauerei lernten wir, dass selbst Gebrautes einfach besser schmeckt.
    Vielen Dank hier an Tobias Lehner und Johannes Federer (die damaligen Braumeister),
    dass ihr unsere Mentoren wart!
  </p>
  <p>
    Das Bedürfnis, gutes Bier zu brauen und natürlich auch zu trinken überdauerte das Studium.
    Wir haben uns mit den nötigen Gerätschaften eingedeckt und unsere ersten
    Fehltritte und Fortschritte erlebt. Seit einiger Zeit finden wir unser Bier auch
    gut genug, dass wir es nicht nur an angeheiterte Kollegen ausschenken,
    sondern auch ganz bewusst an Freunde und Bekannte zum degustieren geben.
  </p>
  <p><em>Die Brauzeugen</em></p>
</section>

<section>
  <h2>Kreationen</h2>

  <p>
    Gutes Bier steht im Zentrum unseres Strebens. Uns ist wichtig, dass wir nicht nachbrauen,
    was auf dem Markt erhältlich ist. Wir wollen Bier das neben dem Charakter und der
    Qualität eine passende Geschichte bietet. So soll es auch nicht immer von gleicher Art sein.
  </p>

  <p><%= link_to 'Zu den Braugängen', brew_batches_path %></p>

</section>

<section>
  <h2>Brauerei</h2>

  <p>
    Die Brauzeugen sind seit 2018 ein Verein nach Schweizer Recht und eingetragene Brauerei mit der
    Registriernummer <a href="https://en.wikipedia.org/wiki/Leet">1337</a>.
    Zum Download findet sich hier das
    <%= link_to 'Statutendokument als PDF', "/files/2018-12-31 Vereinsstatuten Brauzeugen.pdf" %>
    <small>(254KB)</small>
  </p>

  <p>
    Unsere Anschrift ist:
    <address>
      Brauzeugen<br>
      Alte Jonastrasse 12 <br>
      8640 Rapperswil SG
    </address>
  </p>

</section>