config/routes.rb
Rails.application.routes.draw do
  root "home#index"

  resources :brew_batches, only: :index
  get "voices/:token", to: "voices#show", as: :voice
  get "voices/:token/claim", to: "voices#new_claim", as: :claim_voice
  patch "voices/:token/claim", to: "voices#create_claim"

  namespace :admin do
    get "/", to: "pages#dashboard"
    get "/users", to: "pages#users"
    get "/voices", to: "pages#voices"

    resources :brew_batches, except: [:show]
    patch "brew_batches/:id/issue_voices", to: "brew_batches#issue_voices", as: :issue_voices
    get "brew_batches/:id/show_labels", to: "brew_batches#show_labels", as: :show_labels

    resources :releases do
      member do
        patch :notify
      end
    end
  end
end

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Brauzeugen</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'admin', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'admin', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <% flash.each do |key, value| %>
        <div class="<%= flash_class(key) %>">
          <%= value %>
        </div>
      <% end %>

      <header>
        <ul class="list-inline">
          <li class="list-inline-item"><%= link_to 'Dashboard', admin_path %></li>
          <li class="list-inline-item"><%= link_to 'Users', admin_users_path %></li>
          <li class="list-inline-item"><%= link_to 'Voices', admin_voices_path %></li>
          <li class="list-inline-item"><%= link_to 'Brew batches', admin_brew_batches_path %></li>
          <li class="list-inline-item"><%= link_to 'Releases', admin_releases_path %></li>
        </ul>
      </header>

      <%= yield %>
    </div>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Brauzeugen</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <% flash.each do |key, value| %>
        <div class="<%= flash_class(key) %>">
          <%= value %>
        </div>
      <% end %>

      <%= yield %>
    </div>
  </body>

  <script>
    window.onload = function(){
      var elements = document.querySelectorAll('p');
      for (var i=0; i<elements.length; i++){
        elements[i].innerHTML = elements[i].innerHTML.replace(/([.?!]\s+)(\w)/g, "$1<span class='followup-first-letter'>$2</span>")
      }
    }
  </script>
</html>